### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by kyu9341** [boostcamp-2020/IssueTracker-35#1]
![ERD](https://user-images.githubusercontent.com/48315101/97823571-c22d0a00-1cfc-11eb-88e7-002dedb5b847.png)

## --- deprecated ---
![ERD_deprecated](https://user-images.githubusercontent.com/49153756/97160295-78ee2f00-17bf-11eb-89c7-2ffe2482205e.png)

**Comment by joh16** [comment]
comment 테이블을 까먹었네요 야호

**Comment by joh16** [comment]
comment, reaction 등을 반영하여 ERD 수정 완료
