### ISSUE TITLE
nginx에서 세부 경로를 조회했을 때 React Router로 넘어가지 않는 오류

### ISSUE THREAD

**Issue by joh16** [boostcamp-2020/IssueTracker-35#10]
GitHub 로그인을 시도할 때 /users/login/github/callback?code=*** 페이지로 redirect되는데, client에는 index.html밖에 없어 nginx가 이를 인식하지 못하고 404 에러가 뜨는 현상이 있었습니다.

![image](https://user-images.githubusercontent.com/48315101/97658908-e09ec580-1ab0-11eb-9fa9-e437f90089f1.png)

다양한 해결책 중 error 404시 index.html로 직접 redirect하는 방법으로 hotfix를 진행했는데, 이는 존재하지 않는 리소스 조회 시에도 동일하게 적용될 것이므로 수정이 필요할 듯 합니다.

**Comment by kyu9341** [comment]
ㅇㅇ

**Comment by pjy0416** [comment]
- react는 SPA형식으로 index.html만을 사용하지만, nginx의 경우는 URL에 맞는 html파일을 찾으려고 하는 문제가 원인.
- 설정 파일의 location 하단에 server_name $url 설정 파일에 url로 호스트를 설정해줘서 해결
