### ISSUE TITLE
[store] IssueList

### ISSUE THREAD

**Issue by pjy0416** [boostcamp-2020/IssueTracker-35#31]
## 개요
- 이슈 목록의 상태를 관리하는 Store

## 초기 상태
- issues: `[]`
    - [issue 형식](https://github.com/boostcamp-2020/IssueTracker-35/issues/19) 
- selected: `[]`
    - `id`
- timestamp: `new Date()`

## Actions
- `FETCH`
    -  페이지에 진입하며 전체 issue 목록을 받아올 때 발생
    - issues 배열에 해당 id를 추가, timestamp 갱신
- `CHECK`
    - 특정 issue의 체크박스를 선택할 때 발생
    - selected 배열에 해당 id를 추가
- `UNCHECK`
    - 특정 issue의 체크박스를 해제할 때 발생
    - selected 배열에서 해당 id를 제거
- `TOGGLE_ALL`
    - 전체 체크박스의 상태가 바뀔 때 발생
    - selected 배열이 비어 있다면 모든 issue의 id 추가
    - selected 배열이 비어 있지 않다면 비움
- `NEW_ISSUE`
    - 새로운 issue가 작성되었을 때 발생
    - issues 배열에 새로운 issue 추가
    - timestamp 갱신
- `OPEN_ISSUES`
    - Issue 목록 화면에서 선택 후 mark as 드롭다운 -> open을 누를 때 발생
    - Issue 상세 화면에서 Reopen issue 버튼을 누를때 발생
    - issues 갱신, selected 비움, timestamp 갱신
- `CLOSE_ISSUES`
    - Issue 목록 화면에서 선택 후 mark as 드롭다운 -> closed을 누를 때 발생
    - Issue 상세 화면에서 Close issue 버튼을 누를때 발생
    - issues 갱신, selected 비움, timestamp 갱신

**Comment by joh16** [comment]
action 추가, initState 하드코딩 해제(API 연동), reducer 구현
