### ISSUE TITLE
[component] IssueList container

### ISSUE THREAD

**Issue by kyu9341** [boostcamp-2020/IssueTracker-35#45]
## 개요
- 이슈 목록 화면

## 상속 관계
- [Search Container](https://github.com/boostcamp-2020/IssueTracker-35/issues/42)
- [Filter Container](https://github.com/boostcamp-2020/IssueTracker-35/issues/44)
- [IssueItem](https://github.com/boostcamp-2020/IssueTracker-35/issues/46)

## 상태
- [Filter Store](https://github.com/boostcamp-2020/IssueTracker-35/issues/32)
- [IssueList Store](https://github.com/boostcamp-2020/IssueTracker-35/issues/31)

## 세부 동작
- 이슈 목록과 필터를 보여준다.
- [기획서](https://docs.google.com/presentation/d/1iA-tpumHl_TpR_yUwgYcnb_X8GbW6XvjZOTh2Ucvu0A/edit#slide=id.g8582887c3d_0_12)

**Comment by joh16** [comment]
필터 포기
