### ISSUE TITLE
GitHub 로그인 구현

### ISSUE THREAD

**Issue by joh16** [boostcamp-2020/IssueTracker-35#6]
회원가입 페이지에서 Sign in with GitHub 버튼을 눌렀을 때
1. Github 로그인 페이지로 이동, 성공 시 app 승인 code 수령
2. 해당 code로 서버에 인증 요청
  2-1. 해당 사용자가 DB에 등록되어 있지 않다면 등록(login, avatar_url 사용, password는 NULL)
3. 서버가 발급한 JWT 토큰을 localStorage에 저장

이후 이 토큰을 각종 요청의 인증에 사용하도록 구현

[참고자료](https://devhyun.com/blog/post/15)

**Comment by kyu9341** [comment]
1
